### ISSUE TITLE
Change tag / release title

### ISSUE THREAD

**Issue by onedr0p** [cho0o0/calver-release-action#19]
👋🏼 Came across you repo after not discovering much other calver actions out there. I would like the release title to be `2022.12.29.2` instead of `Release ver. 2022.12.29.2` any chance you can make that a knob to turn via an option? Thanks!

**Comment by cho0o0** [comment]
@onedr0p Thanks for your idea. It will be helpful to make the release name customizable. I'd like to work on it later.

**Comment by onedr0p** [comment]
Having a date format option would be nice too but that's up to you 🙂

**Comment by cho0o0** [comment]
@onedr0p 
[2023.01.03.2](https://github.com/marketplace/actions/calver-release-action?version=2023.01.03.2) is out so that you can customize release title via the input parameter. 🎉  
Feel me to raise issues or pull requests if you encountered problems. 

> Having a date format option would be nice too but that's up to you

Exactly. Just want to collect more use cases to see how flexible it should be but customizable version is definitely on my roadmap.

**Comment by onedr0p** [comment]
Thanks!

Maybe to help a bit on how flexible you could make changing the date, I'm just looking for a date format of something like this

`2023.1.1`
